export const LEGACY_SYNCHRONIZED_ACTIONS = [
  'exchangeData',
  'loadDeckData',
  'changeCardBack',
  'reset',
  'setup',
  'takeTurn',
  'draw',
  'moveCardBundle',
  'shuffleIntoDeck',
  'moveToDeckTop',
  'switchWithDeckTop',
  'viewDeck',
  'shuffleAll',
  'shuffleBottom',
  'discardAll',
  'lostZoneAll',
  'handAll',
  'leaveAll',
  'discardAndDraw',
  'shuffleAndDraw',
  'shuffleBottomAndDraw',
  'shufflePrizesToDeckBottom',
  'shuffleZone',
  'useAbility',
  'removeAbilityCounter',
  'addDamageCounter',
  'updateDamageCounter',
  'removeDamageCounter',
  'addSpecialCondition',
  'updateSpecialCondition',
  'removeSpecialCondition',
  'discardBoard',
  'handBoard',
  'shuffleBoard',
  'lostZoneBoard',
  'lookAtCards',
  'stopLookingAtCards',
  'revealCards',
  'hideCards',
  'revealShortcut',
  'hideShortcut',
  'lookShortcut',
  'stopLookingShortcut',
  'playRandomCardFaceDown',
  'rotateCard',
  'changeType',
  'attack',
  'pass',
  'VSTARGXFunction',
  'undo',
] as const;

export const LEGACY_REPLAY_ALLOWED_ACTIONS = [
  'changeCardBack',
  'viewDeck',
  'lookAtCards',
  'stopLookingAtCards',
  'revealCards',
  'hideCards',
  'revealShortcut',
  'hideShortcut',
  'lookShortcut',
  'stopLookingShortcut',
] as const;

export const LEGACY_REPLAY_ALLOWED_KEY_TOKENS = [
  'v',
  'KeyV',
  'c',
  'KeyC',
  'z',
  'KeyZ',
  'r',
  'KeyR',
  'f',
  'KeyF',
  'esc',
  'Escape',
  'Shift',
  'ShiftLeft',
  'ShiftRight',
] as const;

export const LEGACY_REPLAY_ALLOWED_CONTEXT_MENU_IDS = [
  'lookPrizesButton',
  'revealHidePrizesButton',
  'lookHandButton',
  'prizesHeader',
  'handHeader',
  'deckHeader',
  'boardHeader',
] as const;

export const LEGACY_SELECTED_CARD_DESTINATIONS = {
  h: 'hand',
  KeyH: 'hand',
  d: 'discard',
  KeyD: 'discard',
  b: 'bench',
  KeyB: 'bench',
  a: 'active',
  KeyA: 'active',
  g: 'stadium',
  KeyG: 'stadium',
  l: 'lostZone',
  KeyL: 'lostZone',
  p: 'prizes',
  KeyP: 'prizes',
  ' ': 'board',
  KeySpace: 'board',
  ArrowUp: 'deck',
  ArrowDown: 'deck',
  ArrowRight: 'deck',
  s: 'deck',
  KeyS: 'deck',
} as const;

export const LEGACY_KEYBIND_ACTION_CALLS = [
  'addDamageCounter',
  'addSpecialCondition',
  'changeType',
  'discardAndDraw',
  'discardBoard',
  'draw',
  'flipBoard',
  'flipCoin',
  'handBoard',
  'hideShortcut',
  'lookShortcut',
  'moveCardBundle',
  'moveToDeckBottom',
  'moveToDeckTop',
  'reset',
  'revealShortcut',
  'rotateCard',
  'setup',
  'shuffleAll',
  'shuffleAndDraw',
  'shuffleBoard',
  'shuffleBottomAndDraw',
  'shuffleIntoDeck',
  'stopLookingShortcut',
  'switchWithDeckTop',
  'takeTurn',
  'undo',
  'useAbility',
  'viewDeck',
] as const;
