const SVEra = {
    "PAR": {
        159: "pokemon",
        182: "trainer",
        183: "energy",
        235: "pokemon",
        245: "trainer",
        254: "pokemon",
        260: "trainer",
        263: "pokemon",
        266: "trainer",
        267: "energy",
    },
    "MEW": {
        152: "pokemon",
        166: "trainer",
        194: "pokemon",
        198: "trainer",
        203: "pokemon",
        205: "trainer",
        206: "pokemon",
        207: "trainer",
        208: "energy",
    },
    "OBF": {
        186: "pokemon",
        198: "trainer",
        218: "pokemon",
        222: "trainer",
        226: "pokemon",
        228: "trainer",
        229: "pokemon",
        230: "trainer",
        231: "energy",
    },
    "PAL": {
        171: "pokemon",
        190: "trainer",
        194: "energy",
        248: "pokemon",
        256: "trainer",
        265: "pokemon",
        271: "trainer",
        276: "pokemon",
        278: "trainer",
        280: "energy",
    },
    "SVI": {
        166: "pokemon",
        199: "trainer",
        235: "pokemon",
        243: "trainer",
        249: "pokemon",
        253: "trainer",
        255: "pokemon",
        257: "trainer",
        259: "energy",
    },
    "SVP": {
        45: "pokemon",
        46: "trainer",
        102: "pokemon",
    },
};

const SSEra = {
    "CRZ": {
        123: "pokemon",
        152: "trainer",
        160: "energy",
        161: "pokemon",
    },
    "CRZGG": {
        57: "pokemon",
        67: "trainer",
        71: "pokemon",
    },
    "SIT": {
        151: "pokemon",
        168: "trainer",
        170: "energy",
        188: "pokemon",
        196: "trainer",
        203: "pokemon",
        210: "trainer",
        212: "pokemon",
        215: "trainer",
        216: "energy",
    },
    "SITTG": {
        23: "pokemon",
        29: "trainer",
        31: "pokemon",
    },
    "LOR": {
        152: "pokemon",
        171: "trainer",
        172: "energy",
        189: "pokemon",
        197: "trainer",
        204: "pokemon",
        212: "trainer",
        214: "pokemon",
        218: "trainer",
    },
    "LORTG": {
        23: "pokemon",
        29: "trainer",
        31: "pokemon",
    },
    "PGO": {
        64: "pokemon",
        71: "trainer",
        78: "pokemon",
        79: "trainer",
        82: "pokemon",
        86: "trainer",
        87: "pokemon",
        89: "trainer",
    },
    "ASR": {
        135: "pokemon",
        160: "trainer",
        181: "pokemon",
        190: "trainer",
        199: "pokemon",
        208: "trainer",
        211: "pokemon",
        216: "trainer",
        217: "energy",
    },
    "ASRTG": {
        1: "energy",
        24: "pokemon",
        29: "trainer",
        31: "pokemon",
    },
    "BRS": {
        129: "pokemon",
        151: "trainer",
        152: "energy",
        167: "pokemon",
        173: "trainer",
        177: "pokemon",
        181: "trainer",
        185: "pokemon",
        187: "trainer",
    },
    "BRSTG": {
        1: "energy",
        24: "pokemon",
        29: "trainer",
        31: "pokemon",
    },
    "FST": {
        224: "pokemon",
        244: "trainer",
        245: "energy",
        258: "pokemon",
        265: "trainer",
        273: "pokemon",
        280: "trainer",
        281: "pokemon",
        283: "trainer",
        285: "energy",
    },
    "CEL": {
        23: "pokemon",
        25: "trainer",
        26: "pokemon",
    },
    "CELCC": {
        4: "pokemon",
        5: "trainer",
        6: "pokemon",
        7: "trainer",
        12: "pokemon",
        13: "trainer",
        26: "pokemon",
    },
    "EVS": {
        141: "pokemon",
        166: "trainer",
        199: "pokemon",
        204: "trainer",
        221: "pokemon",
        226: "trainer",
        229: "pokemon",
        235: "trainer",
        238: "energy",
    },
    "CRE": {
        129: "pokemon",
        157: "trainer",
        160: "energy",
        186: "pokemon",
        199: "trainer",
        210: "pokemon",
        222: "trainer",
        225: "pokemon",
        231: "trainer",
        233: "energy",
    },
    "BST": {
        121: "pokemon",
        140: "trainer",
        142: "energy",
        158: "pokemon",
        164: "trainer",
        172: "pokemon",
        178: "trainer",
        180: "pokemon",
        182: "trainer",
        184: "energy",
    },
    "SHF": {
        57: "pokemon",
        64: "trainer",
        65: "pokemon",
        73: "trainer",
        74: "pokemon",
    },
    "SHFSV": {
        123: "pokemon",
    },
    "VIV": {
        146: "pokemon",
        162: "trainer",
        166: "energy",
        179: "pokemon",
        186: "trainer",
        192: "pokemon",
        198: "trainer",
        200: "pokemon",
        204: "trainer",
    },
    "CPA": {
        50: "pokemon",
        69: "trainer",
        73: "pokemon",
        74: "trainer",
        77: "pokemon",
        79: "trainer",
        80: "pokemon",
        81: "trainer",
    },
    "DAA": {
        157: "pokemon",
        174: "trainer",
        177: "energy",
        186: "pokemon",
        190: "trainer",
        195: "pokemon",
        197: "trainer",
        199: "pokemon",
        201: "trainer",
        202: "energy",
    },
    "RCL": {
        154: "pokemon",
        171: "trainer",
        175: "energy",
        189: "pokemon",
        193: "trainer",
        200: "pokemon",
        204: "trainer",
        206: "pokemon",
        209: "trainer",
        210: "energy",
    },
    "SSH": {
        156: "pokemon",
        186: "trainer",
        187: "energy",
        199: "pokemon",
        203: "trainer",
        207: "pokemon",
        211: "trainer",
        213: "pokemon",
        217: "trainer",
    },
    "SSP": {
        120: "pokemon",
        122: "trainer",
        146: "pokemon",
        147: "trainer",
        152: "pokemon",
        153: "trainer",
        167: "pokemon",
        168: "trainer",
        178: "pokemon",
        179: "trainer",
        226: "pokemon",
        229: "trainer",
        251: "pokemon",
        252: "trainer",
        296: "pokemon",
        297: "trainer",
        302: "pokemon",
        306: "trainer",
        308: "pokemon",
    },
};

const SMEra = {
    "CEC": {
        185: "pokemon",
        209: "trainer",
        210: "energy",
        228: "pokemon",
        237: "trainer",
        263: "pokemon",
        271: "trainer",
        272: "energy",
    },
    "HIF": {
        51: "pokemon",
        66: "trainer",
        67: "pokemon",
        69: "trainer",
        70: "pokemon",
    },
    "SV": {
        81: "pokemon",
        91: "trainer",
        95: "pokemon",
    },
    "UNM": {
        186: "pokemon",
        212: "trainer",
        214: "energy",
        231: "pokemon",
        237: "trainer",
        250: "pokemon",
        257: "trainer",
        259: "energy",
    },
    "UNB": {
        164: "pokemon",
        190: "trainer",
        191: "energy",
        209: "pokemon",
        215: "trainer",
        229: "pokemon",
        234: "trainer",
        235: "energy",
    },
    "DET": {
        19: "pokemon",
    },
    "TEU": {
        133: "pokemon",
        159: "trainer",
        172: "pokemon",
        182: "trainer",
        192: "pokemon",
        197: "trainer",
    },
    "LOT": {
        167: "pokemon",
        194: "trainer",
        195: "energy",
        208: "pokemon",
        215: "trainer",
        228: "pokemon",
        237: "trainer",
    },
    "DRM": {
        58: "pokemon",
        65: "trainer",
        69: "pokemon",
        71: "trainer",
        75: "pokemon",
        78: "trainer",
        79: "pokemon",
    },
    "CES": {
        123: "pokemon",
        151: "trainer",
        152: "energy",
        161: "pokemon",
        169: "trainer",
        178: "pokemon",
        183: "trainer",
        184: "energy",
    },
    "FLI": {
        102: "pokemon",
        117: "trainer",
        119: "energy",
        128: "pokemon",
        132: "trainer",
        141: "pokemon",
        146: "trainer",
        147: "energy",
    },
    "UPR": {
        118: "pokemon",
        136: "trainer",
        139: "energy",
        148: "pokemon",
        157: "trainer",
        166: "pokemon",
        170: "trainer",
        172: "energy",
        174: "pokemon",
    },
    "CIN": {
        91: "pokemon",
        100: "trainer",
        101: "energy",
        109: "pokemon",
        112: "trainer",
        120: "pokemon",
        122: "trainer",
        125: "energy",
    },
    "SLG": {
        58: "pokemon",
        69: "trainer",
        71: "energy",
        73: "pokemon",
        74: "trainer",
        79: "pokemon",
    },
    "BUS": {
        112: "pokemon",
        129: "trainer",
        142: "pokemon",
        148: "trainer",
        161: "pokemon",
        167: "trainer",
        170: "energy",
    },
    "GRI": {
        116: "pokemon",
        131: "trainer",
        143: "pokemon",
        146: "trainer",
        161: "pokemon",
        166: "trainer",
        170: "energy",
    },
    "SUM": {
        114: "pokemon",
        136: "trainer",
        138: "energy",
        146: "pokemon",
        150: "trainer",
        158: "pokemon",
        162: "trainer",
        164: "energy",
    },
    "SMP": {
        78: "pokemon",
        79: "trainer",
        148: "pokemon",
        149: "trainer",
        231: "pokemon",
        232: "trainer",
        246: "pokemon",
        247: "trainer",
        249: "pokemon",
    },
};

const XYEra = {
    "EVO": {
        73: "pokemon",
        90: "trainer",
        100: "energy",
        107: "pokemon",
        109: "trainer",
        113: "pokemon",
        114: "trainer",
    },
    "STS": {
        98: "pokemon",
        107: "trainer",
        113: "pokemon",
        115: "trainer",
        117: "pokemon",
    },
    "FCO": {
        90: "pokemon",
        114: "trainer",
        116: "energy",
        124: "pokemon",
        125: "trainer",
        126: "pokemon",
    },
    "GEN": {
        59: "pokemon",
        74: "trainer",
        84: "energy",
    },
    "GENRC": {
        1: "energy",
        26: "pokemon",
        28: "trainer",
        33: "pokemon",
    },
    "BKP": {
        96: "pokemon",
        113: "trainer",
        114: "energy",
        122: "pokemon",
        123: "trainer",
        124: "pokemon",
    },
    "BKT": {
        133: "pokemon",
        151: "trainer",
        153: "energy",
        161: "pokemon",
        163: "trainer",
        165: "pokemon",
    },
    "AOR": {
        69: "pokemon",
        82: "trainer",
        84: "energy",
        95: "pokemon",
        96: "trainer",
        99: "pokemon",
        101: "trainer",
    },
    "ROS": {
        83: "pokemon",
        97: "trainer",
        98: "energy",
        107: "pokemon",
        111: "trainer",
    },
    "DCR": {
        23: "pokemon",
        33: "trainer",
        35: "energy",
    },
    "PRC": {
        122: "pokemon",
        143: "trainer",
        145: "energy",
        157: "pokemon",
        165: "trainer",
    },
    "PHF": {
        91: "pokemon",
        111: "trainer",
        113: "energy",
        117: "pokemon",
        120: "trainer",
        123: "pokemon",
    },
    "FFI": {
        88: "pokemon",
        103: "trainer",
        105: "energy",
        109: "pokemon",
        112: "trainer",
        114: "pokemon",
    },
    "FLF": {
        88: "pokemon",
        100: "trainer",
        104: "pokemon",
        107: "trainer",
        110: "pokemon",
    },
    "XY": {
        115: "pokemon",
        130: "trainer",
        141: "energy",
        147: "pokemon",
    },
    "KSS": {
        34: "pokemon",
        40: "trainer",
    },
    "XYP": {
        33: "pokemon",
        34: "trainer",
        99: "pokemon",
        100: "trainer",
        105: "pokemon",
        106: "trainer",
        159: "pokemon",
        160: "trainer",
        169: "pokemon",
        170: "trainer",
        172: "pokemon",
        173: "trainer",
        177: "pokemon",
        179: "trainer",
        199: "pokemon",
        200: "trainer",
        201: "pokemon",
        202: "trainer",
        203: "pokemon",
        212: "trainer",
    },
};

const BWEra = {
    "LTR": {
        109: "pokemon",
        113: "trainer",
        114: "energy",
    },
    "LTRRC": {
        20: "pokemon",
        21: "trainer",
        26: "pokemon",
    },
    "PLB": {
        78: "pokemon",
        91: "trainer",
        92: "energy",
        96: "trainer",
        101: "pokemon",
        102: "trainer",
        105: "pokemon",
        106: "trainer",
    },
    "PLF": {
        99: "pokemon",
        106: "trainer",
        107: "energy",
        109: "trainer",
        115: "pokemon",
        117: "trainer",
        121: "pokemon",
        123: "trainer",
    },
    "PLS": {
        117: "pokemon",
        127: "trainer",
        128: "energy",
        131: "trainer",
        135: "pokemon",
        136: "trainer",
        138: "pokemon",
        139: "trainer",
    },
    "BCR": {
        127: "pokemon",
        141: "trainer",
        147: "pokemon",
        150: "trainer",
        153: "pokemon",
        154: "trainer",
    },
    "DRV": {
        18: "pokemon",
        21: "trainer",
        22: "pokemon",
    },
    "DRX": {
        113: "pokemon",
        117: "trainer",
        119: "energy",
        129: "pokemon",
    },
    "DEX": {
        91: "pokemon",
        103: "trainer",
        111: "pokemon",
        112: "trainer",
    },
    "NXD": {
        86: "pokemon",
        92: "trainer",
        94: "energy",
        104: "pokemon",
    },
    "NVI": {
        90: "pokemon",
        97: "trainer",
        101: "pokemon",
        102: "trainer",
        103: "pokemon",
    },
    "EPO": {
        90: "pokemon",
        97: "trainer",
        99: "pokemon",
    },
    "BLW": {
        92: "pokemon",
        105: "trainer",
        113: "energy",
        116: "pokemon",
    },
    "BWP": {
        28: "pokemon",
        32: "trainer",
        39: "pokemon",
        40: "trainer",
        50: "pokemon",
        51: "trainer",
        95: "pokemon",
        96: "trainer",
        100: "pokemon",
        101: "trainer",
        102: "pokemon",
    },
};

const HSEra = {
    "CL": {
        76: "pokemon",
        86: "trainer",
        96: "energy",
    },
    "CLSL": {
        12: "pokemon",
    },
    "TM": {
        85: "pokemon",
        90: "trainer",
        91: "energy",
        103: "pokemon",
    },
    "UD": {
        71: "pokemon",
        79: "trainer",
        81: "energy",
        91: "pokemon",
    },
    "UL": {
        71: "pokemon",
        84: "trainer",
        96: "pokemon",
    },
    "HS": {
        89: "pokemon",
        103: "trainer",
        105: "energy",
        115: "pokemon",
        123: "energy",
        124: "pokemon",
    },
    "HSP": {
        18: "pokemon",
        19: "trainer",
        26: "pokemon",
    },
};

const setList = {
    ...SVEra,
    ...SSEra,
    ...SMEra,
    ...XYEra,
    ...BWEra,
    ...HSEra,
};

export const getCardType = (setName, cardNumber) => {
    // Function to check for letters at the beginning and separate them
    const separateLettersAndNumbers = (str) => {
        const match = str.match(/^([a-zA-Z]+)(\d+)$/);
        return match ? { letters: match[1], numbers: match[2] } : null;
    };

    // Separate letters from numbers at the beginning of cardNumber
    const separated = separateLettersAndNumbers(cardNumber);

    if (separated) {
        const { letters, numbers } = separated;

        // Update setName and cardNumber accordingly
        setName += letters;
        cardNumber = numbers;
    }

    // Check if the setName is in the dictionary
    if (setList.hasOwnProperty(setName)) {
        // No letters at the beginning, check the regular ranges
        const set = setList[setName];
        const types = Object.values(set);

        for (let i = 0; i < types.length; i++) {
            if (parseInt(cardNumber) < Object.keys(set)[i]) {
                return types[i];
            }
        }
    }

    // Default case if the setName is not found or the cardNumber is too high
    return "Unknown";
};
